#!/usr/bin/env python3
"""
update_threat_feed: pulls OSV.dev npm + PyPI feeds, filters for high-severity
advisories, writes compromised_packages_auto.py next to rules.py.

Run periodically (cron on POSIX, Task Scheduler on Windows). Safe to run while
Claude Code is active: writes via atomic rename so the hook never sees a
half-written file.

Python 3.9+, standard library only.

Usage:
    python update_threat_feed.py
    python update_threat_feed.py --verbose
    python update_threat_feed.py --ecosystem npm
"""

from __future__ import annotations

import argparse
import io
import json
import os
import sys
import urllib.error
import urllib.request
import zipfile
from datetime import datetime, timezone
from pathlib import Path

OSV_SOURCES = {
    "npm":  "https://osv-vulnerabilities.storage.googleapis.com/npm/all.zip",
    "PyPI": "https://osv-vulnerabilities.storage.googleapis.com/PyPI/all.zip",
}

USER_AGENT = "claude-guard-threat-feed/1.0 (+https://anthropic.com)"
TIMEOUT_S = 90

OUT_FILE = Path(__file__).resolve().parent / "compromised_packages_auto.py"


def fetch_zip(url: str, verbose: bool = False) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    if verbose:
        print(f"  Fetching {url}", file=sys.stderr)
    with urllib.request.urlopen(req, timeout=TIMEOUT_S) as resp:
        return resp.read()


def is_malicious_advisory(advisory: dict) -> bool:
    """OSV uses the `MAL-` advisory ID prefix to mark packages that are
    themselves malicious (typosquats, credential stealers, supply-chain
    attacks). This is the right filter for claude-guard's
    "compromised_package" rule.

    Filtering by "any high-severity CVE" instead would include every
    legitimate library that has ever had a security bug (requests, numpy,
    etc.) and produce a flood of false positives at the +60 weight.
    """
    aid = str(advisory.get("id") or "")
    if aid.startswith("MAL-"):
        return True
    for alias in advisory.get("aliases") or []:
        if isinstance(alias, str) and alias.startswith("MAL-"):
            return True
    return False


def packages_from_advisory(advisory: dict) -> list:
    names = []
    for affected in advisory.get("affected", []) or []:
        pkg = affected.get("package") or {}
        name = pkg.get("name")
        if name and isinstance(name, str):
            names.append(name)
    return names


def extract_packages(zip_bytes: bytes, ecosystem: str, verbose: bool = False) -> set:
    found = set()
    total = 0
    malicious = 0
    try:
        z = zipfile.ZipFile(io.BytesIO(zip_bytes))
    except zipfile.BadZipFile as e:
        raise RuntimeError(f"Corrupt zip from {ecosystem}: {e}")
    with z:
        for info in z.infolist():
            if not info.filename.endswith(".json"):
                continue
            total += 1
            try:
                with z.open(info) as f:
                    advisory = json.loads(f.read().decode("utf-8"))
            except (json.JSONDecodeError, UnicodeDecodeError, KeyError):
                continue
            if advisory.get("withdrawn"):
                continue
            if not is_malicious_advisory(advisory):
                continue
            malicious += 1
            for name in packages_from_advisory(advisory):
                found.add(name)
    if verbose:
        print(
            f"  {ecosystem}: scanned {total} advisories, "
            f"{malicious} marked malicious (MAL-*), unique packages: {len(found)}",
            file=sys.stderr,
        )
    return found


def write_module(npm: set, pypi: set, sources: dict) -> None:
    now = datetime.now(timezone.utc).isoformat()
    npm_sorted = sorted(npm)
    pypi_sorted = sorted(pypi)

    lines = [
        "# Auto-generated by update_threat_feed.py. Do not edit by hand;",
        "# rerun the script to refresh. Curated additions belong in rules.py.",
        f"# Generated: {now}",
        f"# npm packages:  {len(npm_sorted)}",
        f"# PyPI packages: {len(pypi_sorted)}",
        "# Sources:",
    ]
    for eco, url in sources.items():
        lines.append(f"#   {eco}: {url}")
    lines.append("")
    lines.append("COMPROMISED_PACKAGES_AUTO = {")
    lines.append("    \"npm\": {")
    for name in npm_sorted:
        lines.append(f"        {repr(name)},")
    lines.append("    },")
    lines.append("    \"pypi\": {")
    for name in pypi_sorted:
        lines.append(f"        {repr(name)},")
    lines.append("    },")
    lines.append("}")
    lines.append("")

    text = "\n".join(lines)

    tmp = OUT_FILE.with_name(OUT_FILE.name + ".tmp")
    tmp.write_text(text, encoding="utf-8", newline="\n")
    os.replace(tmp, OUT_FILE)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Refresh compromised-package list from OSV.dev"
    )
    ap.add_argument("--verbose", "-v", action="store_true")
    ap.add_argument(
        "--ecosystem", choices=("npm", "PyPI", "all"), default="all",
        help="Limit to one ecosystem (useful for tests)",
    )
    args = ap.parse_args()

    selected = (
        OSV_SOURCES if args.ecosystem == "all"
        else {args.ecosystem: OSV_SOURCES[args.ecosystem]}
    )

    npm = set()
    pypi = set()
    try:
        for eco, url in selected.items():
            data = fetch_zip(url, verbose=args.verbose)
            pkgs = extract_packages(data, eco, verbose=args.verbose)
            if eco == "npm":
                npm = pkgs
            elif eco == "PyPI":
                pypi = pkgs
    except urllib.error.URLError as e:
        print(f"update_threat_feed: network error: {e}", file=sys.stderr)
        return 1
    except RuntimeError as e:
        print(f"update_threat_feed: {e}", file=sys.stderr)
        return 1

    # If we only refreshed one ecosystem, preserve the other from the existing
    # file so we don't lose coverage.
    if args.ecosystem != "all" and OUT_FILE.exists():
        try:
            existing_ns = {}
            exec(OUT_FILE.read_text(encoding="utf-8"), existing_ns)
            existing = existing_ns.get("COMPROMISED_PACKAGES_AUTO", {})
            if args.ecosystem != "npm":
                npm = set(existing.get("npm", set()))
            if args.ecosystem != "PyPI":
                pypi = set(existing.get("pypi", set()))
        except Exception:
            pass  # better to write fresh than fail loudly here

    write_module(npm, pypi, OSV_SOURCES)
    print(
        f"Wrote {OUT_FILE.name}: npm={len(npm)} pypi={len(pypi)}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
